# Generated by Django 5.2.1 on 2025-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_sala_alter_mensagem_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='senha',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
