# Generated by Django 5.2.1 on 2025-05-22 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_sala_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
