# Generated by Django 5.2.1 on 2025-06-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_amizade_salaprivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sala',
            name='token',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
