# Generated by Django 5.2.1 on 2025-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemdm',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
