# Generated by Django 5.2.1 on 2025-06-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_mensagem_lida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='lida',
        ),
    ]
